# https://github.com/habx/devops-repo-shared-configs/blob/dev/github-settings/circleci-orb.yml
# 2022-03-19
# last_update: 2022-08-27
_extends: devops-repo-shared-configs:github-settings/circleci-orb.yml
