version: 2.1

python-install-packages: &python-install-packages
  pypi-cache: true
  venv-cache: true
  args: -d --ignore-pipfile

jobs:
  static-tests:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          <<: *python-install-packages
      - run: pipenv run pylint $(find -name "*.py") && pipenv run pycodestyle $(find -name "*.py")

  tests:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          <<: *python-install-packages
      - run: PYTHONPATH=$(pwd) pipenv run pytest --cov-report=xml --cov=.

  checksum-test:
    executor: python/default
    steps:
      - run: |
          echo "go to cache" > cached_file.txt
          echo "Hello World" > test.txt
          ln -s "${PWD}"/test.txt "${PWD}"/test_s_linked.txt
          ls -l
      - save_cache:
          key: from-file-{{ checksum "test.txt" }}
          paths:
            - cached_file.txt
      - save_cache:
          key: from-file-linked-{{ checksum "test_s_linked.txt" }}
          paths:
            - cached_file.txt            


orbs:
  python: circleci/python@2.0.1

workflows:
  tests:
    jobs:
      - tests
      - static-tests
      - checksum-test